# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('domain', models.CharField(max_length=32, unique=True, verbose_name='域名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('remarks', models.CharField(blank=True, max_length=32, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='组')),
                ('remarks', models.CharField(blank=True, max_length=32, null=True, verbose_name='备注')),
                ('asset', models.ManyToManyField(related_name='assetgroups', to='asset.Asset')),
            ],
            options={
                'verbose_name': '组',
                'verbose_name_plural': '组',
            },
        ),
    ]
