# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetgroup',
            name='asset',
            field=models.ManyToManyField(related_name='group', to='asset.Asset'),
        ),
    ]
