# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20181211_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetgroup',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.AssetGroup'),
        ),
    ]
